### ISSUE TITLE
Introducción a async/await en ES7

### ISSUE THREAD

**Issue by impronunciable** [bafrontend/charlas#10]
La charla propone un breve repaso por las técnicas utilizadas para manejar código asíncrono, las mejoras que conlleva el uso de async/await y como se puede usar hoy en día.

**Comment by belohlavek** [comment]
:+1:

**Comment by mgonto** [comment]
+2016 -7

**Comment by mgonto** [comment]
#NerdJoke

**Comment by danzajdband** [comment]
:P

**Comment by impronunciable** [comment]
:100:

**Comment by lucasrudi** [comment]
fijate la charla que hizo ainu en nodejs http://www.slideshare.net/AinuJorgeChambeaudHe/presentacin-sin-ttulo-52932145 en un momento hablo de esto https://github.com/ajchambeaud/charla-node-v4/blob/master/callback/promise.js @ajchambeaud

**Comment by ajchambeaud** [comment]
@lucasrudi en la charla llegamos hasta Generators, porque cubrimos mas que nada el tema de ES2015 en NodeJS. Mencione el tema de async/await pero solo por encima porque forma parte de las propuestas para ES2016 (aunque se que se puede usar hoy con compiladores como babel) 

+1

**Comment by lucasrudi** [comment]
:) gracias ainu, mi idea era dar referencias de una linda charla y material de referencia para verlo en la practica.

**Comment by ajchambeaud** [comment]
Por supuesto, muchas gracias por la mención! Es un tema muy interesante el de manejo de código asincrono en js y en el futuro se vienen cosas muy interesantes. Por ejemplo Observables, que podría ser visto como una combinación entre async/await y generators... Buena idea para una charla por cierto :)

**Comment by impronunciable** [comment]
@lucasrudi @ajchambeaud Buna onda. También hablé de esto en https://getmango.com/blog/pensa-en-serie-ejecuta-en-paralelo-funciones-async-en-javascript/
