### ISSUE TITLE
UX mobile para humanos

### ISSUE THREAD

**Issue by heyimjuani** [bafrontend/charlas#11]
Descripción: 
Cuestiones que en Aerolab dominan la manera de encarar el diseño de un proyecto mobile.

Disertante:
Juani Ruiz Echazu (@heyimjuani)

Tipo:
lightning-talk

**Comment by alevizio** [comment]
+1

**Comment by tinchoforever** [comment]
+2

**Comment by heyimjuani** [comment]
<3

**Comment by belohlavek** [comment]
+3 (? :+1:

**Comment by mgonto** [comment]
-3

**Comment by mgonto** [comment]
@heyimjuani no tiene huevos

**Comment by mgonto** [comment]
@heyimjuani :point_up:

**Comment by sebazelonka** [comment]
+1

**Comment by pazguille** [comment]
@heyimjuani, estamos viendo de armar el meetup para principios de Agosto. Llegas a tener la charla?

**Comment by heyimjuani** [comment]
@pazguille sir, yes sir!

**Comment by pazguille** [comment]
<3
