### ISSUE TITLE
Angular 2: The new horizon

### ISSUE THREAD

**Issue by mgonto** [bafrontend/charlas#12]
Titulo: 
Angular 2: The new horizon

Descripcion:
Everything we used to know (and love?) from Angular 1 has died. No more $scope, services, factories and controllers. Is it good that they died? Why? In this talk, I'll answer those questions and we'll learn all of the key concepts of Angular 2 with a Live Coding demo! Be aware, this session isn't for those faint-hearted.

Speaker:
Gonto

Tipo:
Talk

**Comment by mgonto** [comment]
Esta charla es genial me dijeron

**Comment by mgonto** [comment]
Oh si que buena charla (?)

**Comment by mgonto** [comment]
Quiero quiero

**Comment by mgonto** [comment]
Oh wait, it's just me :raised_hands:

**Comment by mgonto** [comment]
@pazguille eeee poneme el label amigo!

**Comment by mgonto** [comment]
jajajajajaja <3

**Comment by impronunciable** [comment]
+153

**Comment by mgonto** [comment]
@danzajdband <3. Restale a @heyimjuani que su charla es mala

**Comment by okbel** [comment]
+111111111

**Comment by etagwerker** [comment]
:+1:
