### ISSUE TITLE
Firebase: Introducción 

### ISSUE THREAD

**Issue by zapaiamarce** [bafrontend/charlas#13]
Título:
# firebaseIntro

Descripción: 
Introducción al concepto de BAAS (Backend as a service), big JSON, seguridad, libreria y su amistad con Angular. Usos en la vida real.

Disertante:
Marcelo Zapaia (@qzapaia)

Tipo:
talk

**Comment by sebazelonka** [comment]
+1!

**Comment by pazguille** [comment]
@qzapaia Estamos organizando el próximo meetup para septiembre. Nos gustaría que esta sea la charla principal. Cómo venís de tiempos?

**Comment by zapaiamarce** [comment]
Estoy medio complicado para septiembre. Octubre después del 21 me vendría genial.

**Comment by pazguille** [comment]
Dale, lo planificamos para Octubre. Gracias!

**Comment by pazguille** [comment]
@qzapaia, ping! Estamos organizando para el 11 de Noviembre. Te queda cómoda esa fecha para la charla?

**Comment by zapaiamarce** [comment]
Dale. Estoy!

**Comment by pazguille** [comment]
@qzapaia Ya cerramos los speakers, estábamos cortos con el tiempo! :S

**Comment by zapaiamarce** [comment]
No hay problema! Lo vi tarde.
