### ISSUE TITLE
bodymovin: de after effects a svg

### ISSUE THREAD

**Issue by bodymovin** [bafrontend/charlas#19]
Título:
bodymovin. animaciones en html5.

Descripción: 
bodymovin es una libreria en la que estoy trabajando que exporta animaciones hechas en after effects a svg y canvas.
En estos links hay animaciones exportadas con el plugin y el codigo en github.
http://codepen.io/collection/nVYWZR/
https://github.com/bodymovin/bodymovin
La charla es sobre:
- las diferentes alternativas que existen hoy día para animar en la web
- una introducción al plugin
- las nuevas especificaciones de los banners con la partida de flash

Disertante:
Hernan (@airnanan)

Tipo:
lightning talk

**Comment by bodymovin** [comment]
@pazguille che, ya que se hace la charla de modos de animación post flash, no da sumar esta?

**Comment by pazguille** [comment]
Genial! :D

**Comment by pazguille** [comment]
@bodymovin, necesito que me pases una foto tuya y si querés acatualizar la descripción para agregar en el site lo podes hacer (guille87paz at gmail.com)
