### ISSUE TITLE
Cinturón de herramientas del Dev

### ISSUE THREAD

**Issue by sbehrends** [bafrontend/charlas#2]
Título:
# Cinturón de herramientas ~~de Batman~~ del Dev

Descripción:
Como optimizar tareas repetitivas en el flujo de trabajo. Introduccion a grunt.js, sus capacidades y como nos podemos beneficiar mejorando nuestro flujo de trabajo en diferentes proyectos.

Disertante:
Sergio Behrends (gh:@sbehrends - tw:@Blunk)

**Comment by pazguille** [comment]
@sbehrends es una `talk` o `lighting-talk`?

**Comment by sbehrends** [comment]
talk

**Comment by pazguille** [comment]
@sbehrends, estamos viendo de armar el meetup para principios de Agosto. Crees que llegás a tener armada la charla?

**Comment by sbehrends** [comment]
Dale :)
