### ISSUE TITLE
Symbiosis

### ISSUE THREAD

**Issue by fernandezpablo85** [bafrontend/charlas#21]
Título:
Symbiosis: "With great tools come ~~great~~ less responsibility"

Descripción: 
Mis justificaciones de por qué JavaScript es un lenguaje propenso a introducir errores, cómo detectarlos, solucionarlos, y qué alternativas hay.

Disertante:
Pablo Fernandez (@fernandezpablo)

Tipo:
lightning-talk o completa, todavía no la practiqué para ver cuanto dura.

**Comment by fernandezpablo85** [comment]
Algunos contenidos (y el título específicamente) están in progress.

**Comment by davo** [comment]
+1

**Comment by seykron** [comment]
+1

**Comment by seppo0010** [comment]
+1

![cqgvobgukaaqsxk](https://cloud.githubusercontent.com/assets/223776/10180449/2a718d58-66c2-11e5-96ed-8ca482912777.jpg)

**Comment by gerzenstl** [comment]
+1

**Comment by loniszczuk** [comment]
+1
https://www.destroyallsoftware.com/talks/wat

**Comment by fernandezpablo85** [comment]
@loniszczuk me estás arruinando las sorpresas, debe ser por las veces que te bailé(?) en el fútbol de despegar.

**Comment by loniszczuk** [comment]
además de robar en el futbol, te ibas a robar ese video?

**Comment by mgi1982** [comment]
+1

**Comment by vmariano** [comment]
+1 :+1:

**Comment by lucasrudi** [comment]
+1

**Comment by davecaos** [comment]
+1

**Comment by okbel** [comment]
+1

**Comment by lucasrudi** [comment]
+1

**Comment by etagwerker** [comment]
:+1:
