### ISSUE TITLE
Lo que Flash nos dejó (o cómo llenar ese espacio vacío)

### ISSUE THREAD

**Issue by celitwa** [bafrontend/charlas#23]
Título:
Lo que Flash nos dejó (o cómo llenar ese espacio vacío)

Descripción: 
Repasar cómo estamos 5 años después de que Steve Jobs anunció que sus dispositivos no soportaban Flash. Nociones básicas de HTML5 Canvas, SVG y SVG animations, WebGL y cuánto de lo que hacíamos con Flash podemos hacer con estas tecnologías.

Disertante:
Celina Twardowski (@celitwa)

Tipo:
Presentación (30 min).

**Comment by pazguille** [comment]
@celitwa Estamos organizando el próximo meetup para el 11 de Noviembre. Cómo venís de tiempos?

**Comment by celitwa** [comment]
No hay problema! Me encantaría!

**Comment by pazguille** [comment]
Genial! <3
