### ISSUE TITLE
El Zen de Angular

### ISSUE THREAD

**Issue by hrajchert** [bafrontend/charlas#27]
Título: El Zen de Angular

Descripción: 
En esta charla se analiza lo que Angular define como su zen y se ven las diferencias entre un estilo imperativo y uno declarativo no solo en el desarrollo web. Por último, se muestra cómo aplicamos estos conceptos para construir el video player de Acamica 

Disertante: Hernán Rajchert

Tipo: larga duración (40 minutos)

**Comment by pazguille** [comment]
@hrajchert me mandas tu mail :)
