### ISSUE TITLE
Como hacer para que los mejores talentos de Arg laburen gratis para vos.

### ISSUE THREAD

**Issue by abadfederico** [bafrontend/charlas#28]
Título: 3 años de Popcorn Time!

Descripción: La historia de la conformacion del equipo, manejo del proyecto, obstaculos y pensamientos.

Disertante: Federico Abad (@abad)

Tipo: corta duración (20 minutos)

**Comment by inoutux** [comment]
No podías faltar!

Pssst... faltaron los acentos; a la última o de conformación y la a de obstáculos.

**Comment by j0an** [comment]
:+1:

**Comment by etagwerker** [comment]
:+1:

**Comment by pazguille** [comment]
@abadfederico a ver si me contestas por acá. Quedamos para Junio?

**Comment by icarlossz** [comment]
Me copa mucho, algo como lo que hiciste en FuckUp.
