### ISSUE TITLE
UX en Empresas Argentinas

### ISSUE THREAD

**Issue by inoutux** [bafrontend/charlas#29]
Título: UX en Empresas Argentinas

Descripción: ¿Cómo se aplica e impacta hoy día la experiencia de usuario en las plataformas utilizadas?

Disertante: Airin / @Air_Bender_15

Tipo: corta duración (20 minutos)

**Comment by pazguille** [comment]
@airin14 Buenas, para Mayo puede estar la charla?

**Comment by inoutux** [comment]
Hola!

Por supuesto.

Gracias!

Airin

2016-03-08 10:19 GMT-03:00 Guille Paz notifications@github.com:
