### ISSUE TITLE
Tu web deberia funcionar sin JavaScript

### ISSUE THREAD

**Issue by juanigallo** [bafrontend/charlas#30]
Título:
Tu web debería funcionar sin JavaScript

Descripción: 
Demostramos el porque JavaScript debería ser utilizado para mejorar la experiencia de tus usuarios y no un requerimiento en tu aplicación

Disertante:
Juan Gallo @_JuanGallo

Tipo:
corta duración (20 minutos)

**Comment by pazguille** [comment]
@J-Gallo Buenas, estamos organizando las charlas para todo el año. Podes prepararla para el mes de Julio?

**Comment by juanigallo** [comment]
@pazguille Si, no hay drama, puedo prepararla para Julio.

**Comment by pazguille** [comment]
Genial! Ya te anotamos. Cuando tengamos confirmada la fecha hablamos para
coordinar en detalle.

Slds,

Guille Paz
http://pazguille.me
