### ISSUE TITLE
Software a gran escala

### ISSUE THREAD

**Issue by acrosa** [bafrontend/charlas#32]
Título: Todo el software esta roto.

Descripción:
Como industria no podemos asegurar que el software que escribimos va a funcionar correctamente y de manera predecible, en esta charla propongo contar como es el proceso de escribir código que luego es usado por cientos de millones de usuarios. Historias de guerra en LinkedIn y Twitter.

Disertante:
Alejandro Crosa (@alejandrocrosa / @esacrosa)

Tipo: larga duración (40 minutos)

**Comment by seppo0010** [comment]
:+1:

**Comment by pazguille** [comment]
@acrosa En que mes te vamos a ver por acá? Así ya coordinamos :D

**Comment by acrosa** [comment]
A partir del 4 de abril ese mes!

**Comment by okbel** [comment]
:+1:

**Comment by gvilarino** [comment]
:+1: X 8710234975091827340128973

**Comment by argen** [comment]
:+1: Pongan streaming jaja

**Comment by reporteinmobiliario** [comment]
👍

**Comment by j0an** [comment]
:100: x :+1:

**Comment by abadfederico** [comment]
:+1: si no sale hacemos un piquete. abrazame hasta que acrosa vuelva

**Comment by javierder** [comment]
+mil

**Comment by dtluyo** [comment]
Genial 🔥

**Comment by betzerra** [comment]
:+1:

**Comment by fernandezpablo85** [comment]
+1

**Comment by etagwerker** [comment]
:+1: :tada:

**Comment by pazguille** [comment]
@acrosa Listo la agregamos al meetup de abril! :D

**Comment by acrosa** [comment]
Buenísimo gracias!

**Comment by damimj** [comment]
:+1:

**Comment by ssebastianj** [comment]
:+1: al streaming.

**Comment by vmariano** [comment]
:+1: 
 :eggplant: :fist:

**Comment by lucasrudi** [comment]
+1e21

**Comment by runa** [comment]
+1

**Comment by juanrossi** [comment]
:+1:

**Comment by ciroe** [comment]
+1

**Comment by ciroe** [comment]
@acrosa si querés pasar por NXTP Labs a hablar con un par de startups avisame (ciro.echesortu@nxtplabs.com)
