### ISSUE TITLE
SoNowTheFrontIsTheNewBack

### ISSUE THREAD

**Issue by lucasrudi** [bafrontend/charlas#4]
Título:
# SoNowTheFrontIsTheNewBack :)

Descripción: 
El tema de la charla va a ser mostrar los probleamas que un backender tuvo cuando hacia front end y extrapolar eso a la inversa. Entender las limitaciones de tener el backend en el front end, y ver algunas cosas ya exiten.

Disertante:
Lucas Rudi (@ThePiedraStone)

Tipo:
lightning-talk

**Comment by mgonto** [comment]
Me suena el titulo de esta charla :P

**Comment by lucasrudi** [comment]
Hay una foto tuya y todo

**Comment by pazguille** [comment]
@lucasrudi, estamos viendo de armar el meetup para principios de Agosto. Llegas a tener la charla?
