### ISSUE TITLE
Kill float left, hi modern layout!

### ISSUE THREAD

**Issue by israelmw** [bafrontend/charlas#5]
Título:
# Kill float left, hi modern layout!

Descripción: 
Entender porque las practicas comunes de maquetación empiezan a ser obsoletas y surgen nuevas herramientas de HTML/CSS que no solo nos ahorran tiempo sino hacen de nuestras estructuras semánticas un lugar más prolijo y ordenado. Buenas prácticas de maquetación teniendo en cuenta mobile first y escalabilidad basada en código modular. Utilización de pre procesadores de HTML/CSS modernos y con flexibilidad. Y por último adoptar una postura abierta y proactiva en la incorporación constante de nuevas funciones de estándares w3c. 

Disertante:
Israel Wegierski (@israelwegierski)

Tipo:
talk

**Comment by pazguille** [comment]
@israelmw estamos viendo de hacer el meetup el Martes 23 de Junio, llegas para esa fecha con esta charla?

**Comment by debweg** [comment]
Yo voy !

**Comment by j0an** [comment]
+1

**Comment by dmmarmol** [comment]
Yo voy +1
