### ISSUE TITLE
A maintainable Flux

### ISSUE THREAD

**Issue by pazguille** [bafrontend/charlas#7]
Título:
A maintainable Flux

Descripción: 
Vamos a hablar sobre la arquitectura Flux+ReactJS propuesta por Facebook para el desarrollo de aplicaciones fáciles de mantener y que escalen en cantidad de funcionalidades y programadores. Vamos a conocer algunos puntos clave a la hora de trabajar con este pattern y algunos detalles que facilitan el desarrollo de interfaces gráficas ricas e interactivas. Si estás empezando con React o te interesa comenzar a pensar en Flux como arquitectura, esta charla es ideal para vos.

Disertante:
Damian Mendez Romera (@damiar)

Tipo:
talk

**Comment by damianmr** [comment]
Cambiemos el twitter a @damiar :alien: Ya no utilizo más typeofit ;D

**Comment by pazguille** [comment]
:+1:
