### ISSUE TITLE
Langua.js

### ISSUE THREAD

**Issue by turkissh** [bafrontend/charlas#9]
Título:
# Langua.js

Descripción: 
Quiero presentar una libreria opensource para traducir paginas facilmente http://turkissh.github.io/languajs/

Disertante:
Emiliano Di Pierro (@TurKiSsh02)

Tipo:
lightning-talk

**Comment by pazguille** [comment]
@turkissh, estamos viendo de armar el meetup para principios de Agosto. Llegas a tener la charla?

**Comment by turkissh** [comment]
Guille como estas?

al final medio colgue el proyecto porque encontre muy parecido haciendo lo mismo y ya tiene muchisimo mas movimiento de gente.

Igual mil gracias por la oportunidad, nos vemos en la meet, Saludos
